### ISSUE TITLE
npm run build 无效

### ISSUE THREAD

**Issue by jingjingyey** [hanjiangxueying/vue2-iview2-admin#6]
npm run build 无效。。。。。。。。。。
Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\web\vue2-iview2-admin-master\build\build.js:6:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-admin-echarts@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-admin-echarts@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\We\AppData\Roaming\npm-cache\_logs\2018-08-21T08_45_05_452Z-debug.log
这是报错。

**Comment by Blur-mons** [comment]
解决了吗，， 项目写完了， build出问题，要崩了

**Comment by wangxinbo6** [comment]
你把 echarts重新安装一下
